CREATE DATABASE parking_lot;

USE parking_lot;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE parking_slots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slot_number VARCHAR(10) NOT NULL,
    is_disabled_slot BOOLEAN DEFAULT 0,
    available BOOLEAN DEFAULT 1
);

-- Insert 100 slots
INSERT INTO parking_slots (slot_number, is_disabled_slot)
SELECT CONCAT('S', n), IF(n <= 20, 1, 0)
FROM (SELECT @n:=@n+1 as n FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t1,
      (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t2,
      (SELECT @n:=0) t3) t;
